apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: httpd-container
    image: httpd
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: apache-pvc
  volumes:
  - name: apache-pvc
    persistentVolumeClaim:
      claimName: my-pvc
